repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      files: ^backend/
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: .*/__init__.py
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
        files: ^backend/.+.py$
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^backend/.+.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
        files: ^backend/.+.py$
      - id: end-of-file-fixer
        files: ^backend/.+.py$
